# Generated by Django 4.2.7 on 2024-02-28 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tovaru', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='category',
        ),
    ]
