# Generated by Django 4.2.7 on 2024-03-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tovaru', '0003_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Деталь', 'verbose_name_plural': 'Деталі'},
        ),
    ]
